claude_pipeline:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/data/analytics.duckdb'
      extensions:
        - httpfs
      settings:
        s3_endpoint: 'minio:9000'
        s3_access_key_id: 'minioadmin'
        s3_secret_access_key: 'minioadmin123'
        s3_use_ssl: false
        s3_url_style: 'path'