version: 2

models:
  - name: bronze_webhooks
    description: "Deduplicated view of raw webhook data from MinIO"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - not_null
      - name: row_num
        description: "Row number for deduplication (1 = most recent)"

  - name: silver_webhook_events
    description: "Cleaned and categorized webhook events with incremental processing"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - unique
          - not_null
      
      - name: event_type
        description: "Categorized event type"
        tests:
          - accepted_values:
              values: ['solana_swap', 'solana_transaction', 'test_event', 'unknown']
      
      - name: processing_date
        description: "Date of processing"
        tests:
          - not_null
      
      - name: whale_fetch_status
        description: "Status of whale data fetching"
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'fetched', 'failed']
      
      - name: whale_fetched_at
        description: "Timestamp when whale data was fetched"
      
      - name: is_newly_tracked
        description: "Whether this token was newly tracked in current run"
        tests:
          - not_null
      
      - name: has_valid_json
        description: "Whether payload is valid JSON"
        tests:
          - not_null

  - name: silver_transaction_details
    description: "Transaction-specific details for Solana events"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - unique
          - not_null
          - relationships:
              to: ref('silver_webhook_events')
              field: message_id
      
      - name: event_type
        description: "Event type (filtered to transactions only)"
        tests:
          - accepted_values:
              values: ['solana_swap', 'solana_transaction']
      
      - name: transaction_signature
        description: "Solana transaction signature"
        tests:
          - not_null:
              where: "transaction_signature IS NOT NULL"

  - name: silver_data_quality_metrics
    description: "Data quality metrics aggregated by processing date"
    columns:
      - name: processing_date
        description: "Date of processing"
        tests:
          - unique
          - not_null
      
      - name: total_events
        description: "Total number of events processed"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: json_validity_pct
        description: "Percentage of events with valid JSON"
        tests:
          - dbt_utils.expression_is_true:
              expression: "{{ this }}.json_validity_pct >= 0 AND {{ this }}.json_validity_pct <= 100"
      
      - name: unique_message_ids
        description: "Count of unique message IDs"
        tests:
          - dbt_utils.expression_is_true:
              expression: "<= total_events"

  - name: bronze_tokens
    description: "Deduplicated view of token data from BirdEye API with processing state tracking"
    columns:
      - name: token_address
        description: "Unique token contract address"
        tests:
          - unique
          - not_null
      
      - name: processing_date
        description: "Date when token data was processed"
        tests:
          - not_null
      
      - name: processing_status
        description: "Processing state for pipeline tracking"
        tests:
          - not_null
          - accepted_values:
              values: ['unprocessed', 'silver_processed']
      
      - name: silver_processed_at
        description: "Timestamp when processed by silver layer"

  - name: silver_tracked_tokens
    description: "Filtered and enriched tracked tokens for trading analysis"
    columns:
      - name: token_address
        description: "Unique token contract address"
        tests:
          - unique
          - not_null
      
      - name: symbol
        description: "Token symbol"
        tests:
          - not_null
      
      - name: logoURI
        description: "Token logo URI (required for UI display)"
        tests:
          - not_null
      
      - name: liquidity
        description: "Token liquidity in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 10000"
      
      - name: volume24hUSD
        description: "24-hour trading volume in USD"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 50000"
      
      - name: price24hChangePercent
        description: "24-hour price change percentage"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 30"
      
      - name: volume_mcap_ratio
        description: "Volume to market cap ratio"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0.05"
              where: "volume_mcap_ratio IS NOT NULL"
      
      - name: quality_score
        description: "Calculated quality score (0-1 scale)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0 AND quality_score <= 1"
      
      - name: rank
        description: "Liquidity-based ranking (1-50)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 1 AND rank <= 50"
      
      - name: processing_date
        description: "Date of processing"
        tests:
          - not_null
      
      - name: whale_fetch_status
        description: "Status of whale data fetching"
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'fetched', 'failed']
      
      - name: whale_fetched_at
        description: "Timestamp when whale data was fetched"
      
      - name: is_newly_tracked
        description: "Whether this token was newly tracked in current run"
        tests:
          - not_null