FROM apache/airflow:2.10.5

USER root
# Install Java 17 (required for PySpark 3.5.0) and other dependencies
RUN apt-get update && \
    apt-get install -y git openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow
# Install PySpark and other Python dependencies
RUN pip install --no-cache-dir \
    dbt-core \
    dbt-duckdb \
    pyspark==3.5.0 \
    pyarrow \
    boto3 \
    botocore